linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - bodyclose
    - gocritic
    - gocyclo
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - gosqlite3
    - gostyle
    - gosystemd
    - gotype
    - gotypex
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - stylecheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
  gosec:
    excludes:
      - G404
      - G114

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 