version: '3.8'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: battleship
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: battleship
    links:
      - "mongo-db:mongo"

  battleship:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=mongo-db
      - MONGODB_USER=root
      - MONGODB_PASS=battleship
    depends_on:
      - mongo-db

volumes:
  mongo_data_container:
